### ISSUE TITLE
Can this work with items added in Interface Builder instead from code?

### ISSUE THREAD

**Issue by abinop** [honghaoz/ZHAutoScrollView#1]
I am trying to make ZHAutoScrollView work with textfields added as children from within the IB but they are not even clickable. Any idea why?

**Comment by honghaoz** [comment]
I think you can link the text fields in storyboard to the code as IBOutlet, then call `handleTextField:` in `viewDidLoad` to let the scrollView handle the text fields :) let me know whether it works

**Comment by honghaoz** [comment]
@abinop I think you can link the text fields in storyboard to the code as IBOutlets, then call `handleTextField:` in `viewDidLoad` to let the scrollView handle the text fields :) let me know whether it works

**Comment by hash3r** [comment]
@honghaoz unfortunately, it does not work)

**Comment by honghaoz** [comment]
@hash3r Hey hash3r, yes, you are right, you can not set a view as class `AutoScrollView` and add subviews directly on it in IB. Since all text fields should be added on `autoScorllView.contentView`. 

However, we have an another way to use it with IB. Basically, you create a wrapper view or container view for all of views. Then in code, you could add this wrapper view to `autoScrollView.contentView`, just setup some simple full width/height constraints are enough. 

I've pushed a new interface builder demo. Pretty straight forward. Check it out! Let me know if you have more questions :)

**Comment by honghaoz** [comment]
@hash3r Project has been updated and it has an example project with different targets, try it 
![targets](https://raw.githubusercontent.com/honghaoz/AutoKeyboardScrollView/master/Example/select_targets.png)
https://github.com/honghaoz/AutoKeyboardScrollView#work-with-interface-builder
